services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: UserDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migration.workerservice:
    build:
      context: .
      dockerfile: /src/Migration/Migration.WorkerService/Dockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__UserDb: "Host=postgres;Database=UserDb;Username=postgres;Password=postgres"
      ConnectionStrings__CurrencyDb: "Host=postgres;Database=CurrencyDb;Username=postgres;Password=postgres"

  user.grpc:
    build:
      context: .
      dockerfile: src/User/User.Grpc/Dockerfile
    depends_on:
      postgres:
          condition: service_started
      migration.workerservice:
          condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      ConnectionStrings__UserDb: "Host=postgres;Database=UserDb;Username=postgres;Password=postgres"
      Jwt__Secret: "super_secret_key_1234567890!@#$%^&*()"
      Jwt__Issuer: "UserService"
      Jwt__Audience: "InfinityProject"
      ASPNETCORE_URLS: "http://+:8080"
  
  currency.grpc:
    image: ${DOCKER_REGISTRY-}currencygrpc
    build:
      context: .
      dockerfile: src/Currency/Currency.Grpc/Dockerfile
    depends_on:
      postgres:
          condition: service_started
      migration.workerservice:
          condition: service_completed_successfully
    ports:
      - 9080:8080
    environment:
      ConnectionStrings__CurrencyDb: "Host=postgres;Database=CurrencyDb;Username=postgres;Password=postgres"
      Jwt__Secret: "super_secret_key_1234567890!@#$%^&*()"
      Jwt__Issuer: "UserService"
      Jwt__Audience: "InfinityProject"
      ASPNETCORE_URLS: "http://+:8080"

  currency.backgroundworkerservice:
    image: ${DOCKER_REGISTRY-}currencybackgroundworkerservice
    build:
      context: .
      dockerfile: src/Currency/Currency.BackgroundWorkerService/Dockerfile
    depends_on:
      postgres:
          condition: service_started
      #Wait for migration complete
      migration.workerservice:
          condition: service_completed_successfully

    environment:
      ConnectionStrings__CurrencyDb: "Host=postgres;Database=CurrencyDb;Username=postgres;Password=postgres"
      Url__CBCurrencies: "http://www.cbr.ru/scripts/XML_daily.asp"
      BackgroundUpdater_Delay_Seconds: "600"

  gateway.grpc:
    build:
      context: .
      dockerfile: src/Gateway/Gateway.Grpc/Dockerfile
    depends_on:
      currency.grpc:
          condition: service_started
      user.grpc:
          condition: service_started
    ports:
      - 20080:8080
    environment:
      UrlGrpcMicroservice__User: "http://user.grpc:8080"
      UrlGrpcMicroservice__Currency: "http://currency.grpc:8080"
      Jwt__Secret: "super_secret_key_1234567890!@#$%^&*()"
      Jwt__Issuer: "UserService"
      Jwt__Audience: "InfinityProject"
      ASPNETCORE_URLS: "http://+:8080"

  gateway.api:
    build:
      context: .
      dockerfile: src/Gateway/Gateway.Api/Dockerfile
    depends_on:
      currency.grpc:
          condition: service_started
      user.grpc:
          condition: service_started
    ports:
      - 30080:8080
    environment:
      UrlGrpcMicroservice__User: "http://user.grpc:8080"
      UrlGrpcMicroservice__Currency: "http://currency.grpc:8080"
      Jwt__Secret: "super_secret_key_1234567890!@#$%^&*()"
      Jwt__Issuer: "UserService"
      Jwt__Audience: "InfinityProject"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"

volumes:
  pgdata: